Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,8 +24,14 @@ jobs:
     - name: Build Go application
       run: |
         go mod tidy
-        go build -o password-generator main.go
-        ls -l
+        go build -o build/password-generator main.go
+
+    - name: Verify binary exists
+      run: |
+        if [ ! -f build/password-generator ]; then
+          echo "Error: Binary not found!"
+          exit 1
+        fi
 
     - name: Copy HTML and CSS
       run: |
@@ -46,6 +52,7 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-1
 
-    - name: Deploy Build to AWS S3
+    - name: Deploy Build to AWS S3 (if needed)
+      if: always()
       run: |
         aws s3 cp build/ s3://cloudhub-devops13/apps/${{ github.event.inputs.version }}/ --recursive
